
export const Routes = {
    // pages
    ZealHome: { path: "/" },
    DashboardOverview: { path: "/overview" },
    SearchTeammates: {path: "/dashboard/search"},
    Transactions: { path: "/transactions" },
    Profile: { path: "/profile" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/signin" },
    Signup: { path: "/signup" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/404" },
    ServerError: { path: "/500" },
    FAQ: { path: "/faq" },
    Gotcha: { path: "/gotcha" },
    Notes: { path: "/notes" },
    Calender: { path: "/calendar" },
    Chat: { path: "/chat" },
    ParticipantEvents: { path: "/participantevents" },
    OrganizerEvents: { path: "/organizerevents" },
    ViewParticipateEvent: { path: "/view_participate_event" },
    ViewOrganizerPastEvent: { path: "/view_organizer_past_event" },
    ViewParticipantPastEvent: { path: "/view_participant_past_event" },
    OrganizerEventDashboard: { path: "/edit_organizer_event" },
    ParticipantEventDashboard : { path: "/participant_event_dashboard" },
    TeamVisualizer : { path: "/team_visualizer" },
    ParticipantTeamOwnerDetails : { path: "/participant_team_owner_details" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" },

    // Statics
    email: { path: "support@zeal.courses" }
};